language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wosniuxx"             # 填写你的GitHub用户名
  - git config user.email "wosniuxx@163.com"          # 填写你的GitHub注册邮箱
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master                                # 此处为源文件所在的仓库分支，默认master
env:
 global:
   - GH_REF: git@github.com:wosniuxx/dblog.git       # 此处为静态文件仓库，也就是你设定GitHub Pages的仓库地址
